### ISSUE TITLE
Add Gaussian smoothing to processed_data

### ISSUE THREAD

**Issue by amjcosta** [codeforgoodconf/black_holes_backend#4]
We may need to add Gaussian smoothing to the[ processed_data](https://github.com/codeforgoodconf/black_holes_backend/blob/master/processed_data/classified-2017-07-30-09-53-33.csv). @rlbyrne had worked on this with previous data processing.

**Comment by rlbyrne** [comment]
To do Gaussian smoothing to reduce data noise see the module gaussian_smooth in data_preprocess/preprocess_pipe.py

**Comment by sauln** [comment]
Kamino closed and cloned this issue to codeforgoodconf/black_holes
